#ifndef CUSTMENU_DSPF_H
#define CUSTMENU_DSPF_H

#include <string>

// Auto-generated by dspfc — do not edit

struct MAINMENU_buf {
    char OPTION[2] = {};
};

struct CUSTDSP_buf {
    char CUSTNO[11] = {};
    char CUSTNAME[51] = {};
    double CUSTBAL = 0.0;
    char ERRMSG[79] = {};
};

struct CONFIRM_buf {
    char ANSWER[2] = {};
};

#endif // CUSTMENU_DSPF_H
