#include "extdesc.h"
#include <algorithm>
#include <cctype>
#include <cstring>
#include <fstream>
#include <iostream>
#include <regex>
#include <sstream>

// ODBC headers — only included when building extdesc
#ifdef _WIN32
#  define WIN32_LEAN_AND_MEAN
#  include <windows.h>
#endif
#include <sql.h>
#include <sqlext.h>

static std::string toUpper(std::string s) {
    for (auto& c : s) c = static_cast<char>(toupper(static_cast<unsigned char>(c)));
    return s;
}

static std::string toLower(std::string s) {
    for (auto& c : s) c = static_cast<char>(tolower(static_cast<unsigned char>(c)));
    return s;
}

static std::string trim(const std::string& s) {
    size_t a = s.find_first_not_of(" \t\r\n");
    size_t b = s.find_last_not_of(" \t\r\n");
    return (a == std::string::npos) ? "" : s.substr(a, b - a + 1);
}

// Map ODBC SQL type → ExtField cppType / bindKind
static void mapSqlType(SQLSMALLINT sqlType, SQLULEN colSize, SQLSMALLINT decDigits,
                        ExtField& f) {
    switch (sqlType) {
        case SQL_CHAR:
        case SQL_VARCHAR:
        case SQL_LONGVARCHAR:
        case SQL_WCHAR:
        case SQL_WVARCHAR:
            f.cppType  = "std::string";
            f.bindKind = "str";
            f.length   = static_cast<int>(colSize);
            break;
        case SQL_SMALLINT:
        case SQL_INTEGER:
        case SQL_TINYINT:
        case SQL_BIGINT:
            f.cppType  = "long";
            f.bindKind = "int";
            f.length   = static_cast<int>(colSize);
            break;
        case SQL_NUMERIC:
        case SQL_DECIMAL:
        case SQL_FLOAT:
        case SQL_REAL:
        case SQL_DOUBLE:
            f.cppType  = "double";
            f.bindKind = "dbl";
            f.length   = static_cast<int>(colSize);
            f.decimals = static_cast<int>(decDigits);
            break;
        case SQL_TYPE_DATE:
        case SQL_TYPE_TIME:
        case SQL_TYPE_TIMESTAMP:
            f.cppType  = "std::string";
            f.bindKind = "str";
            f.length   = 26;
            break;
        default:
            f.cppType  = "std::string";
            f.bindKind = "str";
            f.length   = static_cast<int>(colSize ? colSize : 256);
            break;
    }
}

// Write .extdesc cache file
static void writeCache(const std::string& path, const ExternalFileDesc& desc) {
    std::ofstream f(path);
    if (!f.is_open()) return;
    f << "# auto-generated by rpgc — safe to commit\n";
    f << "table=" << desc.tableName << "\n";
    for (auto& fld : desc.fields) {
        f << fld.name << " " << fld.cppType;
        if (fld.length > 0) f << "(" << fld.length;
        if (fld.decimals > 0) f << ":" << fld.decimals;
        if (fld.length > 0) f << ")";
        f << " " << fld.bindKind << "\n";
    }
}

// Read .extdesc cache file
static bool readCache(const std::string& path, ExternalFileDesc& desc) {
    std::ifstream f(path);
    if (!f.is_open()) return false;
    std::string line;
    while (std::getline(f, line)) {
        if (line.empty() || line[0] == '#') continue;
        if (line.substr(0, 6) == "table=") {
            desc.tableName = trim(line.substr(6));
            continue;
        }
        // field line: NAME cpptype(len:dec) bindkind
        std::istringstream ss(line);
        ExtField ef;
        std::string typestr, bindkind;
        ss >> ef.name >> typestr >> bindkind;
        if (ef.name.empty() || typestr.empty()) continue;
        // parse cpptype and optional (len:dec)
        auto paren = typestr.find('(');
        if (paren != std::string::npos) {
            std::string inner = typestr.substr(paren + 1);
            if (!inner.empty() && inner.back() == ')') inner.pop_back();
            typestr = typestr.substr(0, paren);
            auto colon = inner.find(':');
            if (colon != std::string::npos) {
                ef.length   = std::stoi(inner.substr(0, colon));
                ef.decimals = std::stoi(inner.substr(colon + 1));
            } else {
                ef.length = std::stoi(inner);
            }
        }
        ef.cppType  = typestr;
        ef.bindKind = bindkind.empty() ? "str" : bindkind;
        desc.fields.push_back(ef);
    }
    return !desc.fields.empty() || !desc.tableName.empty();
}

// Query ODBC for one table's columns
static bool queryODBC(SQLHDBC hdbc, const std::string& tableName, ExternalFileDesc& desc) {
    SQLHSTMT hstmt = SQL_NULL_HSTMT;
    if (SQLAllocHandle(SQL_HANDLE_STMT, hdbc, &hstmt) != SQL_SUCCESS) return false;

    // SQLColumns: catalog=NULL, schema=NULL, table=tableName, column=NULL
    SQLRETURN rc = SQLColumns(hstmt,
        nullptr, 0,
        nullptr, 0,
        (SQLCHAR*)tableName.c_str(), SQL_NTS,
        nullptr, 0);

    if (rc != SQL_SUCCESS && rc != SQL_SUCCESS_WITH_INFO) {
        SQLFreeHandle(SQL_HANDLE_STMT, hstmt);
        return false;
    }

    // Bind result columns we care about: col 4 = COLUMN_NAME, 5 = DATA_TYPE,
    // 6 = TYPE_NAME, 7 = COLUMN_SIZE, 9 = DECIMAL_DIGITS
    char colName[256] = {};
    SQLSMALLINT dataType = 0;
    SQLULEN colSize = 0;
    SQLSMALLINT decDigits = 0;
    SQLLEN indName = 0, indType = 0, indSize = 0, indDec = 0;

    SQLBindCol(hstmt, 4, SQL_C_CHAR,   colName,   sizeof(colName), &indName);
    SQLBindCol(hstmt, 5, SQL_C_SSHORT, &dataType, 0,               &indType);
    SQLBindCol(hstmt, 7, SQL_C_ULONG,  &colSize,  0,               &indSize);
    SQLBindCol(hstmt, 9, SQL_C_SSHORT, &decDigits,0,               &indDec);

    bool found = false;
    while ((rc = SQLFetch(hstmt)) == SQL_SUCCESS || rc == SQL_SUCCESS_WITH_INFO) {
        ExtField ef;
        ef.name = toUpper(std::string(colName, (indName > 0) ? (size_t)indName : strlen(colName)));
        mapSqlType(dataType, colSize, decDigits, ef);
        desc.fields.push_back(ef);
        found = true;
    }

    SQLFreeHandle(SQL_HANDLE_STMT, hstmt);
    return found;
}

// Extract DCL-F DISK file names from source text (fast regex scan, before full parse)
static std::vector<std::pair<std::string, std::string>>
scanDclF(const std::string& src) {
    // Match: DCL-F <name> DISK [optional keywords including EXTDESC('tablename')]
    std::vector<std::pair<std::string, std::string>> result; // {rpgName, extdescOverride}
    std::regex dclf_re(R"(DCL-F\s+(\w+)\s+DISK\b([^;]*);)",
                        std::regex::icase);
    std::regex extdesc_re(R"(EXTDESC\s*\(\s*'([^']*)'\s*\))",
                           std::regex::icase);

    auto begin = std::sregex_iterator(src.begin(), src.end(), dclf_re);
    auto end   = std::sregex_iterator();
    for (auto it = begin; it != end; ++it) {
        std::smatch m = *it;
        std::string rpgName = toUpper(m[1].str());
        std::string rest    = m[2].str();
        std::string override_table;
        std::smatch em;
        if (std::regex_search(rest, em, extdesc_re)) {
            override_table = em[1].str();
        }
        result.emplace_back(rpgName, override_table);
    }
    return result;
}

std::map<std::string, ExternalFileDesc>
queryExternalDescs(const std::string& src_text,
                   const std::string& src_dir,
                   const RpgConf& conf) {
    std::map<std::string, ExternalFileDesc> result;

    auto files = scanDclF(src_text);
    if (files.empty()) return result;

    // Try to establish ODBC connection if conf has DSN
    SQLHENV henv = SQL_NULL_HENV;
    SQLHDBC hdbc = SQL_NULL_HDBC;
    bool connected = false;

    if (!conf.db_dsn.empty()) {
        SQLAllocHandle(SQL_HANDLE_ENV, SQL_NULL_HANDLE, &henv);
        SQLSetEnvAttr(henv, SQL_ATTR_ODBC_VERSION, (void*)SQL_OV_ODBC3, 0);
        SQLAllocHandle(SQL_HANDLE_DBC, henv, &hdbc);
        SQLCHAR outConn[1024] = {};
        SQLSMALLINT outLen = 0;
        SQLRETURN rc = SQLDriverConnect(hdbc, nullptr,
            (SQLCHAR*)conf.db_dsn.c_str(), SQL_NTS,
            outConn, sizeof(outConn), &outLen,
            SQL_DRIVER_NOPROMPT);
        connected = (rc == SQL_SUCCESS || rc == SQL_SUCCESS_WITH_INFO);
    }

    std::string prefix = src_dir.empty() ? "" : src_dir + "/";

    for (auto& [rpgName, override_table] : files) {
        ExternalFileDesc desc;
        std::string tableName = override_table.empty() ? toLower(rpgName) : override_table;
        desc.tableName = tableName;

        std::string cachePath = prefix + rpgName + ".extdesc";

        if (connected) {
            // Try live query first
            if (queryODBC(hdbc, tableName, desc) && !desc.fields.empty()) {
                writeCache(cachePath, desc);
                result[rpgName] = desc;
                continue;
            }
        }

        // Fall back to cache
        ExternalFileDesc cached;
        if (readCache(cachePath, cached) && !cached.fields.empty()) {
            if (cached.tableName.empty()) cached.tableName = tableName;
            result[rpgName] = cached;
        } else if (!desc.fields.empty()) {
            result[rpgName] = desc;
        }
        // If neither DB nor cache has it, leave it out — codegen will emit a comment
    }

    if (connected) {
        SQLDisconnect(hdbc);
        SQLFreeHandle(SQL_HANDLE_DBC, hdbc);
        SQLFreeHandle(SQL_HANDLE_ENV, henv);
    }

    return result;
}
